spring:
  redis:
    host: 172.23.16.58
    password: dzxx5859
    database: 11
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
  cache:
    redis:
      use-key-prefix: true
      time-to-live: 60s